apiVersion: v1
kind: Service
metadata:
  name: resume-client
  namespace: resume-builder
spec:
  type: LoadBalancer
  selector:
    app: resume-client
  ports:
  - port: 80
    targetPort: 80
    name: http


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-client
  namespace: resume-builder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-client
  template:
    metadata:
      labels:
        app: resume-client
    spec:
      containers:
      - name: client
        image: vaibdan/resume-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: resume-config