apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-builder-config
  namespace: resume-builder
data:
  NODE_ENV: "production"
  PORT: "3000"
  # Frontend talks to the backend via the internal K8s service name
  VITE_API_URL: "http://resume-server:3000"
  # ALLOWED_ORIGINS: "http://localhost:8080,http://localhost. * "
  ALLOWED_ORIGINS: "http://k8s-resumebu-resumebu-46224ab0ad-1771661039.us-east-1.elb.amazonaws.com"