apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resume-server-hpa
  namespace: resume-builder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resume-server
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resume-client-hpa
  namespace: resume-builder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resume-client
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
